/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.car.visao;

import com.car.Ferramentas.ConexaoBD;
import com.car.Ferramentas.JTableRenderer;
import com.car.Modelos.Marcas;
import com.car.Modelos.Modelos;
import com.car.persistencia.IMarcasDAO;
import com.car.persistencia.IModelosDAO;
import com.car.persistencia.MarcasDAO;
import com.car.persistencia.ModelosDAO;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;

/**
 *
 * @author Pichau
 */
public class TelaModelos extends javax.swing.JFrame {

    IMarcasDAO marcasBD = null;
    private Connection conexao = null;
    PreparedStatement st;

    public TelaModelos() {
        
        try {
            conexao = ConexaoBD.getConexao();
        } catch (Exception ex) {
            Logger.getLogger(TelaModelos.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();

        jTextField1_IDModelos.setEnabled(false);

        GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Rectangle bounds = env.getMaximumWindowBounds();
        setLocationRelativeTo(null);
        int largura = bounds.width;
        int altura = bounds.height;
        setSize(largura, altura);
        setLocation(0, 0);

        
        IModelosDAO modelosBD = null;
        try {
            modelosBD = new ModelosDAO();
            imprimirDadosNaGrid(modelosBD.listagemDeModelos());
        } catch (Exception e) {
        }
        
        
        try {
            puxarDadosComboBox();
        } catch (Exception ex) {
            Logger.getLogger(TelaModelos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4_voltar = new javax.swing.JButton();
        BuscarMarcas = new javax.swing.JButton();
        ImagensModelos = new javax.swing.JLabel();
        ImagensMarcas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton_Remover = new javax.swing.JButton();
        jButton_Alterar = new javax.swing.JButton();
        jButton_iNCLUIR = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_tabelaModelos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel11_marcasModelos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1_IDModelos = new javax.swing.JTextField();
        jTextField1_DescricaoModelo = new javax.swing.JTextField();
        jComboBox1_ListaMarcas = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1_urlImagens = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/car/visao/icons/pinkLogoMenorzinha.gif"))); // NOI18N
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Bodoni MT", 3, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("MARCAS");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, 40));

        jLabel13.setFont(new java.awt.Font("Bodoni MT", 3, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("MODELO");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 160, -1, 40));

        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 330, -1));

        jButton4_voltar.setBackground(new java.awt.Color(255, 255, 255));
        jButton4_voltar.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        jButton4_voltar.setForeground(new java.awt.Color(255, 51, 153));
        jButton4_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/car/visao/icons/voltar.png"))); // NOI18N
        jButton4_voltar.setText("VOLTAR");
        jButton4_voltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton4_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 630, 140, 40));

        BuscarMarcas.setBackground(new java.awt.Color(255, 255, 255));
        BuscarMarcas.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        BuscarMarcas.setForeground(new java.awt.Color(255, 51, 153));
        BuscarMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/car/visao/icons/buscarImagemIcon.png"))); // NOI18N
        BuscarMarcas.setText("  BUSCAR");
        BuscarMarcas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        BuscarMarcas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuscarMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarMarcasActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 200, 140, 40));

        ImagensModelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/car/visao/icons/PinkImages.gif"))); // NOI18N
        ImagensModelos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(ImagensModelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 230, 190));

        ImagensMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/car/visao/icons/PinkImages.gif"))); // NOI18N
        ImagensMarcas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(ImagensMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 230, 190));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Bodoni MT", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CADASTRO DE MODELOS");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 480, 40));

        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(836, 200, -1, 190));

        jButton_Remover.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Remover.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        jButton_Remover.setForeground(new java.awt.Color(255, 51, 153));
        jButton_Remover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/car/visao/icons/removeriten.png"))); // NOI18N
        jButton_Remover.setText("REMOVER");
        jButton_Remover.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton_Remover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoverActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Remover, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 350, 140, 40));

        jButton_Alterar.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Alterar.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        jButton_Alterar.setForeground(new java.awt.Color(255, 51, 153));
        jButton_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/car/visao/icons/alterar.png"))); // NOI18N
        jButton_Alterar.setText("ALTERAR");
        jButton_Alterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton_Alterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 300, 140, 40));

        jButton_iNCLUIR.setBackground(new java.awt.Color(255, 255, 255));
        jButton_iNCLUIR.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        jButton_iNCLUIR.setForeground(new java.awt.Color(255, 51, 153));
        jButton_iNCLUIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/car/visao/icons/adicionarItens.png"))); // NOI18N
        jButton_iNCLUIR.setText("  INCLUIR");
        jButton_iNCLUIR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton_iNCLUIR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_iNCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_iNCLUIRActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_iNCLUIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 250, 140, 40));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 204, 330, -1));

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 204)));

        jTable1_tabelaModelos.setBackground(new java.awt.Color(153, 153, 153));
        jTable1_tabelaModelos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTable1_tabelaModelos.setFont(new java.awt.Font("Bodoni MT", 3, 26)); // NOI18N
        jTable1_tabelaModelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "MARCA", "", "MODELO", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1_tabelaModelos.setRequestFocusEnabled(false);
        jTable1_tabelaModelos.setRowHeight(75);
        jTable1_tabelaModelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_tabelaModelosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_tabelaModelos);
        if (jTable1_tabelaModelos.getColumnModel().getColumnCount() > 0) {
            jTable1_tabelaModelos.getColumnModel().getColumn(1).setPreferredWidth(170);
            jTable1_tabelaModelos.getColumnModel().getColumn(2).setPreferredWidth(0);
            jTable1_tabelaModelos.getColumnModel().getColumn(3).setPreferredWidth(170);
            jTable1_tabelaModelos.getColumnModel().getColumn(4).setPreferredWidth(0);
            jTable1_tabelaModelos.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 800, 250));

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("DESCRIÇÃO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, 40));

        jLabel11_marcasModelos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel11_marcasModelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 230, 190));

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("MARCA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, 40));

        jLabel10.setFont(new java.awt.Font("Bodoni MT", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, 40));

        jTextField1_IDModelos.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1_IDModelos.setFont(new java.awt.Font("Bodoni MT", 3, 22)); // NOI18N
        jTextField1_IDModelos.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1_IDModelos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jTextField1_IDModelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 130, 40));

        jTextField1_DescricaoModelo.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1_DescricaoModelo.setFont(new java.awt.Font("Bodoni MT", 3, 22)); // NOI18N
        jTextField1_DescricaoModelo.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1_DescricaoModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jTextField1_DescricaoModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 320, 40));

        jComboBox1_ListaMarcas.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        jComboBox1_ListaMarcas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jComboBox1_ListaMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_ListaMarcasActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1_ListaMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 180, 40));

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 94, 480, -1));

        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4), "OPÇÕES", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bodoni MT", 3, 20), new java.awt.Color(0, 0, 0))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 1030, 280));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/car/visao/icons/FundoTelas.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextField1_urlImagens.setText("jTextField1");
        getContentPane().add(jTextField1_urlImagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_voltarActionPerformed
        // TODO add your handling code here:
        TelaPrincipal principal = new TelaPrincipal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4_voltarActionPerformed

    private void BuscarMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarMarcasActionPerformed
        try {
            JFileChooser fc = new JFileChooser("./src/com/car/imagensModelos");
            File buscar = new File(".src/com/car/imagensModelos");

            fc.setCurrentDirectory(buscar);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.showOpenDialog(this);
            File arquivo = fc.getSelectedFile();
            String nomeDoArquivo = arquivo.getPath();
            jTextField1_urlImagens.setText(nomeDoArquivo);
            ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
            iconLogo.setImage(iconLogo.getImage().getScaledInstance(
                    ImagensMarcas.getWidth(), ImagensMarcas.getHeight(), 1));
            ImagensMarcas.setIcon(iconLogo);
            ImagensModelos.setVisible(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_BuscarMarcasActionPerformed

    private void jButton_RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoverActionPerformed
        try {
            IModelosDAO modelosDAO = null;
            modelosDAO = new ModelosDAO();
            modelosDAO.excluir(Integer.parseInt(jTextField1_IDModelos.getText()));
            limparTela();
            imprimirDadosNaGrid(modelosDAO.listagemDeModelos());
            ImagensModelos.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton_RemoverActionPerformed

    public void puxarDadosComboBox() throws Exception {
        try {
            MarcasDAO marcasDAO = new MarcasDAO();
            ResultSet rs = marcasDAO.listarMarcas();
            while (rs.next()) {
                jComboBox1_ListaMarcas.addItem(rs.getString(1));
            }

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "combobox");
        }
    }

    public void puxarImagemMarca() throws Exception {
        try {

            MarcasDAO marcas = new MarcasDAO();
            Modelos mod = new Modelos();

            ArrayList<Marcas> lista = marcas.listaDeMarcas();
            for (int i = 0; i < lista.size(); i++) {
                ImageIcon marca = new ImageIcon(lista.get(i).getUrl());
                if (jComboBox1_ListaMarcas.getSelectedItem().equals(lista.get(i).getDescricao())) {

                    marca.setImage(marca.getImage().getScaledInstance(jLabel11_marcasModelos.getWidth(), jLabel11_marcasModelos.getHeight(), 1));
                    jLabel11_marcasModelos.setIcon(marca);
                }
            }

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "combobox");
        }
    }

    public void limparTela() {
        jTextField1_IDModelos.setText("");
        jTextField1_urlImagens.setText("");
        jTextField1_DescricaoModelo.setText("");
    }

    private void imprimirDadosNaGrid(ArrayList<Modelos> listagemDeModelos) {

        try {
            DefaultTableModel model = (DefaultTableModel) jTable1_tabelaModelos.getModel();
            JTableRenderer JtableRenderer = new JTableRenderer();
            

            model.setNumRows(0);
            
            Statement statement = conexao.createStatement();
            String query = "select idmodelos as id, marcas.descricao AS  marcas, descricaomodelos as modelo, urlmodelos , imagemmodelo from modelos\n" +
                           "join marcas on marcas.idmarcas = modelos.idmarcas";
            ResultSet resultSet = statement.executeQuery(query);
            
//            String imagem = "SELECT urlmodelos FROM modelos";
//            ImageIcon iconlogo = new ImageIcon(resultSet.getString(imagem));
//            System.out.println(iconlogo);
            
              
            DefaultTableModel tableModel = new DefaultTableModel();
            jTable1_tabelaModelos.setModel(tableModel);
            
            // Obter os metadados do resultado da consulta
            ResultSetMetaData metaData = resultSet.getMetaData();
            int columnCount = metaData.getColumnCount();

            // Adicionar as colunas à tabela
            for (int i = 1; i <= columnCount; i++) {
                tableModel.addColumn(metaData.getColumnName(i));
            }

            // Adicionar as linhas à tabela
            while (resultSet.next()) {
                Object[] row = new Object[columnCount];
                for (int i = 1; i <= columnCount; i++) {
                    row[i - 1] = resultSet.getObject(i);
                }
                tableModel.addRow(row);
            }
            jTable1_tabelaModelos.getColumnModel().getColumn(4).setCellRenderer(JtableRenderer);
           
            jTable1_tabelaModelos.getColumnModel().getColumn(3).setWidth(0);
            jTable1_tabelaModelos.getColumnModel().getColumn(3).setMinWidth(0);
            jTable1_tabelaModelos.getColumnModel().getColumn(3).setMaxWidth(0);

            // Fechar a conexão com o banco de dados
            resultSet.close();
            statement.close();
            
            
//            Iterator<Modelos> lista = listagemDeModelos.iterator();
//
//            while (lista.hasNext()) {
//                String[] saida = new String[4];
//                Modelos aux = lista.next();
//                saida[0] = aux.getIdModelos() + "";
//                saida[1] = aux.getMarca().getDescricao();
//                saida[2] = aux.getDescricao();
//                saida[3] = aux.getUrl();
//
//                ImageIcon iconlogo = new ImageIcon((aux.getUrl()));
//                ImageIcon marca = new ImageIcon((aux.getMarca().getUrl()));
//                
//                Object[] dados = {saida[0], saida[1], marca,  saida[2], saida[3],iconlogo};
//                model.addRow(dados);
//
//            }


        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }

    private void jButton_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AlterarActionPerformed

    }//GEN-LAST:event_jButton_AlterarActionPerformed

    private void jButton_iNCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_iNCLUIRActionPerformed
        try {
            File fis = new File(jTextField1_urlImagens.getText());
            IModelosDAO modelooo = null;
            modelooo = new ModelosDAO();
            IMarcasDAO marcaaaa = null;
            marcaaaa = new MarcasDAO();

            int busc = 0;
            Modelos modelo = null;
            modelo = new Modelos(0, marcaaaa.listaDeMarcas().get(busc),
                    jTextField1_DescricaoModelo.getText(), jTextField1_urlImagens.getText(), fis);

            ArrayList<Marcas> lista = marcaaaa.listaDeMarcas();
            for (int i = 0; i < lista.size(); i++) {
                if (jComboBox1_ListaMarcas.getSelectedItem().equals(lista.get(i).getDescricao())) {
                    modelo.setMarca(lista.get(i));
                }
            }

            IModelosDAO modelosDAO = null;
            modelosDAO = new ModelosDAO();
            modelosDAO.inserirModelos(modelo);
            limparTela();
            ImagensModelos.setVisible(true);
            imprimirDadosNaGrid(modelosDAO.listagemDeModelos());
            jComboBox1_ListaMarcas.setSelectedIndex(0);
        } catch (Exception err) {
            JOptionPane.showMessageDialog(this, err);
        }
    }//GEN-LAST:event_jButton_iNCLUIRActionPerformed

    private void jTable1_tabelaModelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_tabelaModelosMouseClicked
        jTextField1_IDModelos.setText(jTable1_tabelaModelos.getValueAt(jTable1_tabelaModelos.getSelectedRow(), 0).toString());
        jTextField1_DescricaoModelo.setText(jTable1_tabelaModelos.getValueAt(jTable1_tabelaModelos.getSelectedRow(), 2).toString());
        jTextField1_urlImagens.setText(jTable1_tabelaModelos.getValueAt(jTable1_tabelaModelos.getSelectedRow(), 3).toString());
        String nomeDoArquivo = jTextField1_urlImagens.getText();
        ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
        iconLogo.setImage(iconLogo.getImage().getScaledInstance(
                ImagensModelos.getWidth(), ImagensModelos.getHeight(), 1));
        ImagensMarcas.setIcon(iconLogo);
        ImagensModelos.setVisible(false);
        
        jComboBox1_ListaMarcas.setSelectedItem(jTable1_tabelaModelos.getValueAt(jTable1_tabelaModelos.getSelectedRow(), 1).toString());
        
    }//GEN-LAST:event_jTable1_tabelaModelosMouseClicked

    private void jComboBox1_ListaMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_ListaMarcasActionPerformed

        try {
            puxarImagemMarca();
        } catch (Exception ex) {
            Logger.getLogger(TelaModelos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox1_ListaMarcasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaModelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaModelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaModelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaModelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaModelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarMarcas;
    private javax.swing.JLabel ImagensMarcas;
    private javax.swing.JLabel ImagensModelos;
    private javax.swing.JButton jButton4_voltar;
    private javax.swing.JButton jButton_Alterar;
    private javax.swing.JButton jButton_Remover;
    private javax.swing.JButton jButton_iNCLUIR;
    private javax.swing.JComboBox<String> jComboBox1_ListaMarcas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel11_marcasModelos;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_tabelaModelos;
    private javax.swing.JTextField jTextField1_DescricaoModelo;
    private javax.swing.JTextField jTextField1_IDModelos;
    private javax.swing.JTextField jTextField1_urlImagens;
    // End of variables declaration//GEN-END:variables
}
