/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.car.visao;

import com.car.Ferramentas.JTableRenderer;
import com.car.Modelos.Marcas;
import com.car.persistencia.IMarcasDAO;
import com.car.persistencia.MarcasDAO;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pichau
 */
public class telaMarcas extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public telaMarcas() {
        initComponents();

        GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Rectangle bounds = env.getMaximumWindowBounds();
        int largura = bounds.width;
        int altura = bounds.height;
        setSize(largura, altura);
        setLocation(0, 0);

        jTextField1_IDMarcas.setEnabled(false);

        IMarcasDAO marcasBD = null;
        try {
            marcasBD = new MarcasDAO();
            imprimirDadosNaGrid(marcasBD.listaDeMarcas());
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton4_voltar = new javax.swing.JButton();
        BuscarMarcas = new javax.swing.JButton();
        ImagensMarcas1 = new javax.swing.JLabel();
        ImagensMarcas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_Remover = new javax.swing.JButton();
        jButton_Alterar = new javax.swing.JButton();
        jButton_iNCLUIR = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_tabelaMarcas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1_IDMarcas = new javax.swing.JTextField();
        jTextField1_DescricaoMarca1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1_urlImagens = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/car/visao/icons/PingAnimatedLogo.gif"))); // NOI18N
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton4_voltar.setBackground(new java.awt.Color(0, 0, 0));
        jButton4_voltar.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        jButton4_voltar.setForeground(new java.awt.Color(255, 0, 153));
        jButton4_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/car/visao/icons/voltar.png"))); // NOI18N
        jButton4_voltar.setText("VOLTAR");
        jButton4_voltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton4_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 630, 130, 40));

        BuscarMarcas.setBackground(new java.awt.Color(0, 0, 0));
        BuscarMarcas.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        BuscarMarcas.setForeground(new java.awt.Color(255, 0, 153));
        BuscarMarcas.setText("BUSCAR");
        BuscarMarcas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        BuscarMarcas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuscarMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarMarcasActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 190, 130, 40));

        ImagensMarcas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/car/visao/icons/PinkImages.gif"))); // NOI18N
        ImagensMarcas1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(ImagensMarcas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 230, 190));

        ImagensMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/car/visao/icons/insiraImagem.gif"))); // NOI18N
        ImagensMarcas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(ImagensMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 230, 190));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Bodoni MT", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CADASTRO DE MARCAS");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 470, 30));

        jButton_Remover.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Remover.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        jButton_Remover.setForeground(new java.awt.Color(255, 0, 153));
        jButton_Remover.setText("REMOVER");
        jButton_Remover.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton_Remover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoverActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Remover, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 340, 130, 40));

        jButton_Alterar.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Alterar.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        jButton_Alterar.setForeground(new java.awt.Color(255, 0, 153));
        jButton_Alterar.setText("ALTERAR");
        jButton_Alterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton_Alterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 290, 130, 40));

        jButton_iNCLUIR.setBackground(new java.awt.Color(0, 0, 0));
        jButton_iNCLUIR.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        jButton_iNCLUIR.setForeground(new java.awt.Color(255, 0, 153));
        jButton_iNCLUIR.setText("INCLUIR");
        jButton_iNCLUIR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton_iNCLUIR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_iNCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_iNCLUIRActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_iNCLUIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 240, 130, 40));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, 40));

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 204)));

        jTable1_tabelaMarcas.setBackground(new java.awt.Color(153, 153, 153));
        jTable1_tabelaMarcas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTable1_tabelaMarcas.setFont(new java.awt.Font("Bodoni MT", 3, 24)); // NOI18N
        jTable1_tabelaMarcas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "DESCRIÇÃO", "", "LOGO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1_tabelaMarcas.setRowHeight(60);
        jTable1_tabelaMarcas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_tabelaMarcasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_tabelaMarcas);
        if (jTable1_tabelaMarcas.getColumnModel().getColumnCount() > 0) {
            jTable1_tabelaMarcas.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable1_tabelaMarcas.getColumnModel().getColumn(2).setPreferredWidth(0);
            jTable1_tabelaMarcas.getColumnModel().getColumn(2).setHeaderValue("");
            jTable1_tabelaMarcas.getColumnModel().getColumn(3).setPreferredWidth(210);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 710, 250));

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("DESCRIÇÃO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, 40));

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, 40));

        jTextField1_IDMarcas.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1_IDMarcas.setFont(new java.awt.Font("Bodoni MT", 3, 22)); // NOI18N
        jTextField1_IDMarcas.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1_IDMarcas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jTextField1_IDMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 130, 40));

        jTextField1_DescricaoMarca1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1_DescricaoMarca1.setFont(new java.awt.Font("Bodoni MT", 3, 22)); // NOI18N
        jTextField1_DescricaoMarca1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1_DescricaoMarca1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jTextField1_DescricaoMarca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 460, 40));

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 450, -1));

        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4), "OPÇÕES", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bodoni MT", 3, 22), new java.awt.Color(0, 0, 0))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 390, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/car/visao/icons/FundoTelas.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextField1_urlImagens.setText("jTextField1");
        getContentPane().add(jTextField1_urlImagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_voltarActionPerformed
        // TODO add your handling code here:
        TelaPrincipal principal = new TelaPrincipal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4_voltarActionPerformed

    private void BuscarMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarMarcasActionPerformed
        try {
            JFileChooser fc = new JFileChooser("./src/com/car/imagensMarcas");
            File buscar = new File(".src/com/car/imagensMarcas");

            fc.setCurrentDirectory(buscar);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.showOpenDialog(this);
            File arquivo = fc.getSelectedFile();
            String nomeDoArquivo = arquivo.getPath();
            jTextField1_urlImagens.setText(nomeDoArquivo);
            ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
            iconLogo.setImage(iconLogo.getImage().getScaledInstance(ImagensMarcas.getWidth(), ImagensMarcas.getHeight(), 1));
            ImagensMarcas.setIcon(iconLogo);
            ImagensMarcas1.setVisible(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_BuscarMarcasActionPerformed

    private void jButton_RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoverActionPerformed
        try {
            IMarcasDAO marcasDao = null;
            marcasDao = new MarcasDAO();
            marcasDao.excluirMarca(Integer.parseInt(jTextField1_IDMarcas.getText()));
            limparTela();
            imprimirDadosNaGrid(marcasDao.listaDeMarcas());
            ImagensMarcas1.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton_RemoverActionPerformed

    private void jButton_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AlterarActionPerformed
        try {
            IMarcasDAO marcasDAO = null;
            marcasDAO = new MarcasDAO();
            alterarMarca();
            limparTela();
            imprimirDadosNaGrid(marcasDAO.listaDeMarcas());
            ImagensMarcas1.setVisible(true);
        } catch (Exception err) {
            JOptionPane.showMessageDialog(this, err);
        }
    }//GEN-LAST:event_jButton_AlterarActionPerformed

    private void jButton_iNCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_iNCLUIRActionPerformed
        try {
            File fis = new File(jTextField1_urlImagens.getText());
            Marcas marca = null;
            marca = new Marcas(0, jTextField1_DescricaoMarca1.getText(), jTextField1_urlImagens.getText(), fis);

            IMarcasDAO marcasDAO = null;
            marcasDAO = new MarcasDAO();
            marcasDAO.InserirMarca(marca);
            limparTela();
            ImagensMarcas1.setVisible(true);
            imprimirDadosNaGrid(marcasDAO.listaDeMarcas());
        } catch (Exception err) {
            JOptionPane.showMessageDialog(this, err);
        }
    }//GEN-LAST:event_jButton_iNCLUIRActionPerformed

    private void jTable1_tabelaMarcasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_tabelaMarcasMouseClicked
        jTextField1_IDMarcas.setText(jTable1_tabelaMarcas.getValueAt(jTable1_tabelaMarcas.getSelectedRow(), 0).toString());
        jTextField1_DescricaoMarca1.setText(jTable1_tabelaMarcas.getValueAt(jTable1_tabelaMarcas.getSelectedRow(), 1).toString());
        jTextField1_urlImagens.setText(jTable1_tabelaMarcas.getValueAt(jTable1_tabelaMarcas.getSelectedRow(), 2).toString());
        String nomeDoArquivo = jTextField1_urlImagens.getText();
        ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
        iconLogo.setImage(iconLogo.getImage().getScaledInstance(
                ImagensMarcas.getWidth(), ImagensMarcas.getHeight(), 1));
        ImagensMarcas.setIcon(iconLogo);
        ImagensMarcas1.setVisible(false);
    }//GEN-LAST:event_jTable1_tabelaMarcasMouseClicked

    public void limparTela() {
        jTextField1_IDMarcas.setText("");
        jTextField1_urlImagens.setText("");
        jTextField1_DescricaoMarca1.setText("");
    }

    private void alterarMarca() {
        try {
            File fis = new File(jTextField1_urlImagens.getText());
            Marcas marcas = new Marcas(Integer.parseInt(jTextField1_IDMarcas.getText()), jTextField1_DescricaoMarca1.getText(),
                    jTextField1_urlImagens.getText(), fis);

            MarcasDAO marc = new MarcasDAO();
            marc.alterarMarca(marcas);
        } catch (Exception err) {
            JOptionPane.showMessageDialog(this, err);
        }
    }

    private void imprimirDadosNaGrid(ArrayList<Marcas> listaDeMarcas) {

        try {
            DefaultTableModel model = (DefaultTableModel) jTable1_tabelaMarcas.getModel();
            JTableRenderer JtableRenderer = new JTableRenderer();
            jTable1_tabelaMarcas.getColumnModel().getColumn(3).setCellRenderer(JtableRenderer);

            model.setNumRows(0);
            Iterator<Marcas> lista = listaDeMarcas.iterator();

            while (lista.hasNext()) {
                String[] saida = new String[3];
                Marcas aux = lista.next();
                saida[0] = aux.getId() + "";
                saida[1] = aux.getDescricao();
                saida[2] = aux.getUrl();

                ImageIcon iconlogo = new ImageIcon((aux.getUrl()));
                Object[] dados = {saida[0], saida[1], saida[2], iconlogo};
                model.addRow(dados);

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaMarcas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarMarcas;
    private javax.swing.JLabel ImagensMarcas;
    private javax.swing.JLabel ImagensMarcas1;
    private javax.swing.JButton jButton4_voltar;
    private javax.swing.JButton jButton_Alterar;
    private javax.swing.JButton jButton_Remover;
    private javax.swing.JButton jButton_iNCLUIR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_tabelaMarcas;
    private javax.swing.JTextField jTextField1_DescricaoMarca1;
    private javax.swing.JTextField jTextField1_IDMarcas;
    private javax.swing.JTextField jTextField1_urlImagens;
    // End of variables declaration//GEN-END:variables
}
